In [1]:
import pandas as pd
import numpy as np

In [2]:
cust = pd.read_csv("Customers.csv", encoding="latin1",sep=";")
cust.head(10)

  Customer ID         Customer Name
0    AA-10315            Alex Avila
1    AA-10375          Allen Armold
2    AA-10480          Andrew Allen
3    AA-10645         Anna Andreadi
4    AB-10015         Aaron Bergman
5    AB-10060       Adam Bellavance
6    AB-10105         Adrian Barton
7    AB-10150           Aimee Bixby
8    AB-10165           Alan Barnes
9    AB-10255  Alejandro Ballentine

In [3]:
cust.shape

(793, 2)

In [4]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    793 non-null    object
 1   Customer Name  793 non-null    object
dtypes: object(2)
memory usage: 12.5+ KB

In [5]:
cust.isnull().sum()

Customer ID      0
Customer Name    0
dtype: int64

In [6]:
cust.duplicated().sum()

np.int64(0)

In [7]:
cust.nunique()

Customer ID      793
Customer Name    793
dtype: int64

In [8]:
cust.to_excel(
    r"C:\Users\AmanGogna\OneDrive - techcarrot.ae\Desktop\Customers_Transformed.xlsx",
    index=False
)

------------------------------------------------------

In [26]:
loct = pd.read_csv("Location.csv", encoding="latin1",sep=";")
loct.head(10)

   Postal Code        City      State   Region Country/Region
0      76106.0  Fort Worth      Texas  Central  United States
1      53711.0     Madison  Wisconsin  Central  United States
2      68025.0     Fremont   Nebraska  Central  United States
3      77095.0     Houston      Texas  Central  United States
4      75080.0  Richardson      Texas  Central  United States
5      77041.0     Houston      Texas  Central  United States
6      60540.0  Naperville   Illinois  Central  United States
7      55122.0       Eagan  Minnesota  Central  United States
8      48185.0    Westland   Michigan  Central  United States
9      47150.0  New Albany    Indiana  Central  United States

In [27]:
loct.shape

(632, 5)

In [28]:
loct.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 632 entries, 0 to 631
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Postal Code     631 non-null    float64
 1   City            632 non-null    object
 2   State           632 non-null    object
 3   Region          632 non-null    object
 4   Country/Region  632 non-null    object
dtypes: float64(1), object(4)
memory usage: 24.8+ KB

In [29]:
loct.isnull().sum()

Postal Code       1
City              0
State             0
Region            0
Country/Region    0
dtype: int64

In [30]:
loct.duplicated().sum()

np.int64(0)

In [31]:
loct.nunique()

Postal Code       630
City              531
State              49
Region              4
Country/Region      1
dtype: int64

In [32]:
loct[loct["State"] == "Texas"].head(10)

    Postal Code           City  State   Region Country/Region
0       76106.0     Fort Worth  Texas  Central  United States
3       77095.0        Houston  Texas  Central  United States
4       75080.0     Richardson  Texas  Central  United States
5       77041.0        Houston  Texas  Central  United States
12      77070.0        Houston  Texas  Central  United States
23      78207.0    San Antonio  Texas  Central  United States
24      77036.0        Houston  Texas  Central  United States
26      75051.0  Grand Prairie  Texas  Central  United States
27      75220.0         Dallas  Texas  Central  United States
31      77506.0       Pasadena  Texas  Central  United States

In [33]:
loct.to_excel(
    r"C:\Users\AmanGogna\OneDrive - techcarrot.ae\Desktop\Location_Transformed.xlsx",
    index=False
)

In [34]:
loct = loct.drop_duplicates(subset=["Postal Code"])

In [35]:
loct

     Postal Code             City       State   Region Country/Region
0        76106.0       Fort Worth       Texas  Central  United States
1        53711.0          Madison   Wisconsin  Central  United States
2        68025.0          Fremont    Nebraska  Central  United States
3        77095.0          Houston       Texas  Central  United States
4        75080.0       Richardson       Texas  Central  United States
..           ...              ...         ...      ...            ...
627      83301.0       Twin Falls       Idaho     West  United States
628      92672.0     San Clemente  California     West  United States
629      94568.0           Dublin  California     West  United States
630      93405.0  San Luis Obispo  California     West  United States
631      95240.0             Lodi  California     West  United States

[631 rows x 5 columns]

In [38]:
loct.to_excel(
    r"C:\Users\AmanGogna\OneDrive - techcarrot.ae\Desktop\Location_Transformed_again.xlsx",
    index=False
)

In [40]:
print("Total Rows:", len(loct))

Total Rows: 631

In [42]:
print("Unique Postal Codes:", loct["Postal Code"].nunique())

Unique Postal Codes: 630

In [43]:
print("Duplicate Postal Codes:", loct["Postal Code"].duplicated().sum())

Duplicate Postal Codes: 0

In [57]:
loct_dim = loct.drop_duplicates(subset=["Postal Code"])

print(loct_dim.shape)

(631, 5)

In [59]:
loct.to_excel(
    r"C:\Users\AmanGogna\OneDrive - techcarrot.ae\Desktop\Location_Transformed_again_again.xlsx",
    index=False
)

In [60]:
loct = loct.dropna(subset=["Postal Code"])

In [61]:
loct.isnull().sum()

Postal Code       0
City              0
State             0
Region            0
Country/Region    0
dtype: int64

In [62]:
loct.to_excel(
    r"C:\Users\AmanGogna\OneDrive - techcarrot.ae\Desktop\Location_Transformed_again_a.xlsx",
    index=False
)

-------------------------------------------------------

In [45]:
orders = pd.read_csv(
    "Orders.csv",encoding="latin1",
    sep=";",
    decimal=","
)
orders

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Postal Code,Product ID,Sales,Quantity,Discount,Profit
0,1,CA-2022-152156,08/11/2022,11/11/2022,Second Class,CG-12520,Consumer,42420,FUR-BO-10001798,261.9600,2,0.00,41.9136
1,2,CA-2022-152156,08/11/2022,11/11/2022,Second Class,CG-12520,Consumer,42420,FUR-CH-10000454,731.9400,3,0.00,219.5820
2,3,CA-2022-138688,12/06/2022,16/06/2022,Second Class,DV-13045,Corporate,90036,OFF-LA-10000240,14.6200,2,0.00,6.8714
3,4,US-2021-108966,11/10/2021,18/10/2021,Standard Class,SO-20335,Consumer,33311,FUR-TA-10000577,957.5775,5,0.45,-383.0310
4,5,US-2021-108966,11/10/2021,18/10/2021,Standard Class,SO-20335,Consumer,33311,OFF-ST-10000760,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2020-110422,21/01/2020,23/01/2020,Second Class,TB-21400,Consumer,33180,FUR-FU-10001889,25.2480,3,0.20,4.1028
9990,9991,CA-2023-121258,26/02/2023,03/03/2023,Standard Class,DB-13060,Consumer,92627,FUR-FU-10000747,91.9600,2,0.00,15.6332
9991,9992,CA-2023-121258,26/02/2023,03/03/2023,Standard Class,DB-13060,Consumer,92627,TEC-PH-10003645,258.5760,2,0.20,19.3932
9992,9993,CA-2023-121258,26/02/2023,03/03/2023,Standard Class,DB-13060,Consumer,92627,OFF-PA-10004041,29.6000,4,0.00,13.3200
9993,9994,CA-2023-119914,04/05/2023,09/05/2023,Second Class,CC-12220,Consumer,92683,OFF-AP-10002684,243.1600,2,0.00,72.9480

In [46]:
orders.shape

(9994, 13)

In [47]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Row ID       9994 non-null   int64
 1   Order ID     9994 non-null   object
 2   Order Date   9994 non-null   object
 3   Ship Date    9994 non-null   object
 4   Ship Mode    9994 non-null   object
 5   Customer ID  9994 non-null   object
 6   Segment      9994 non-null   object
 7   Postal Code  9994 non-null   int64
 8   Product ID   9994 non-null   object
 9   Sales        9994 non-null   float64
 10  Quantity     9994 non-null   int64
 11  Discount     9994 non-null   float64
 12  Profit       9994 non-null   float64
dtypes: float64(3), int64(3), object(7)
memory usage: 1015.1+ KB

In [48]:
orders.isnull().sum()

Row ID         0
Order ID       0
Order Date     0
Ship Date      0
Ship Mode      0
Customer ID    0
Segment        0
Postal Code    0
Product ID     0
Sales          0
Quantity       0
Discount       0
Profit         0
dtype: int64

In [49]:
orders.duplicated().sum()

np.int64(0)

In [50]:
orders.nunique()

Row ID         9994
Order ID       5009
Order Date     1236
Ship Date      1334
Ship Mode         4
Customer ID     793
Segment           3
Postal Code     630
Product ID     1862
Sales          5825
Quantity         14
Discount         12
Profit         7287
dtype: int64

In [51]:
orders[(orders["Ship Mode"] == "Second Class") & (orders["Segment"] == "Consumer")].head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Postal Code,Product ID,Sales,Quantity,Discount,Profit
0,1,CA-2022-152156,08/11/2022,11/11/2022,Second Class,CG-12520,Consumer,42420,FUR-BO-10001798,261.960,2,0.0,41.9136
1,2,CA-2022-152156,08/11/2022,11/11/2022,Second Class,CG-12520,Consumer,42420,FUR-CH-10000454,731.940,3,0.0,219.5820
17,18,CA-2020-167164,13/05/2020,15/05/2020,Second Class,AG-10270,Consumer,84084,OFF-ST-10000107,55.500,2,0.0,9.9900
18,19,CA-2020-143336,27/08/2020,01/09/2020,Second Class,ZD-21925,Consumer,94109,OFF-AR-10003056,8.560,2,0.0,2.4824
19,20,CA-2020-143336,27/08/2020,01/09/2020,Second Class,ZD-21925,Consumer,94109,TEC-PH-10001949,213.480,3,0.2,16.0110
20,21,CA-2020-143336,27/08/2020,01/09/2020,Second Class,ZD-21925,Consumer,94109,OFF-BI-10002215,22.720,4,0.2,7.3840
23,24,US-2023-156909,16/07/2023,18/07/2023,Second Class,SF-20065,Consumer,19140,FUR-CH-10002774,71.372,2,0.3,-1.0196
25,26,CA-2022-121755,16/01/2022,20/01/2022,Second Class,EH-13945,Consumer,90049,OFF-BI-10001634,11.648,2,0.2,4.2224
26,27,CA-2022-121755,16/01/2022,20/01/2022,Second Class,EH-13945,Consumer,90049,TEC-AC-10003027,90.570,3,0.0,11.7741
46,47,CA-2020-146703,20/10/2020,25/10/2020,Second Class,PO-18865,Consumer,48185,OFF-ST-10001713,211.960,4,0.0,8.4784

In [52]:
orders["Order Date"] = pd.to_datetime(
    orders["Order Date"],
    format="%d/%m/%Y"
)
orders["Ship Date"] = pd.to_datetime(
    orders["Ship Date"],
    format="%d/%m/%Y"
)

In [54]:
orders.to_excel(
    r"C:\Users\AmanGogna\OneDrive - techcarrot.ae\Desktop\Orders_Transformed.xlsx",
    index=False
)

In [55]:
print("Total Rows:", len(orders))

Total Rows: 9994

In [56]:
print("Unique Postal Codes:", orders["Postal Code"].nunique())

Unique Postal Codes: 630

-------------------------------------------

In [10]:
prod = pd.read_csv("Products.csv", encoding="latin1",sep=";")
prod.head(10)

,Product ID,Category,Sub-Category,Product Name
0,FUR-BO-10000112,Furniture,Bookcases,"Bush Birmingham Collection Bookcase, Dark Cherry"
1,FUR-BO-10000330,Furniture,Bookcases,"Sauder Camden County Barrister Bookcase, Plank..."
2,FUR-BO-10000362,Furniture,Bookcases,Sauder Inglewood Library Bookcases
3,FUR-BO-10000468,Furniture,Bookcases,O'Sullivan 2-Shelf Heavy-Duty Bookcases
4,FUR-BO-10000711,Furniture,Bookcases,"Hon Metal Bookcases, Gray"
5,FUR-BO-10000780,Furniture,Bookcases,O'Sullivan Plantations 2-Door Library in Landv...
6,FUR-BO-10001337,Furniture,Bookcases,O'Sullivan Living Dimensions 2-Shelf Bookcases
7,FUR-BO-10001519,Furniture,Bookcases,O'Sullivan 3-Shelf Heavy-Duty Bookcases
8,FUR-BO-10001567,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Dark Cher..."
9,FUR-BO-10001601,Furniture,Bookcases,"Sauder Mission Library with Doors, Fruitwood F..."

In [11]:
prod.shape

(1894, 4)

In [12]:
prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1894 entries, 0 to 1893
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    1894 non-null   object
 1   Category      1894 non-null   object
 2   Sub-Category  1894 non-null   object
 3   Product Name  1894 non-null   object
dtypes: object(4)
memory usage: 59.3+ KB

In [13]:
prod.isnull().sum()

Product ID      0
Category        0
Sub-Category    0
Product Name    0
dtype: int64

In [14]:
prod.duplicated().sum()

np.int64(0)

In [15]:
prod.nunique()

Product ID      1862
Category           3
Sub-Category      17
Product Name    1849
dtype: int64

In [16]:
prod[(prod["Category"]=="Furniture") & (prod["Sub-Category"]=="Bookcases")].head(10)

,Product ID,Category,Sub-Category,Product Name
0,FUR-BO-10000112,Furniture,Bookcases,"Bush Birmingham Collection Bookcase, Dark Cherry"
1,FUR-BO-10000330,Furniture,Bookcases,"Sauder Camden County Barrister Bookcase, Plank..."
2,FUR-BO-10000362,Furniture,Bookcases,Sauder Inglewood Library Bookcases
3,FUR-BO-10000468,Furniture,Bookcases,O'Sullivan 2-Shelf Heavy-Duty Bookcases
4,FUR-BO-10000711,Furniture,Bookcases,"Hon Metal Bookcases, Gray"
5,FUR-BO-10000780,Furniture,Bookcases,O'Sullivan Plantations 2-Door Library in Landv...
6,FUR-BO-10001337,Furniture,Bookcases,O'Sullivan Living Dimensions 2-Shelf Bookcases
7,FUR-BO-10001519,Furniture,Bookcases,O'Sullivan 3-Shelf Heavy-Duty Bookcases
8,FUR-BO-10001567,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Dark Cher..."
9,FUR-BO-10001601,Furniture,Bookcases,"Sauder Mission Library with Doors, Fruitwood F..."

In [17]:
prod.to_excel(
    r"C:\Users\AmanGogna\OneDrive - techcarrot.ae\Desktop\Products_Transformed.xlsx",
    index=False
)

In [19]:
prod["Product ID"].duplicated().sum()

np.int64(32)

In [21]:
prod["Product ID"].nunique()

1862

In [22]:
len(prod)

1894

In [24]:
prod = prod.drop_duplicates(subset=["Product ID"])

In [36]:
prod

,Product ID,Category,Sub-Category,Product Name
0,FUR-BO-10000112,Furniture,Bookcases,"Bush Birmingham Collection Bookcase, Dark Cherry"
1,FUR-BO-10000330,Furniture,Bookcases,"Sauder Camden County Barrister Bookcase, Plank..."
2,FUR-BO-10000362,Furniture,Bookcases,Sauder Inglewood Library Bookcases
3,FUR-BO-10000468,Furniture,Bookcases,O'Sullivan 2-Shelf Heavy-Duty Bookcases
4,FUR-BO-10000711,Furniture,Bookcases,"Hon Metal Bookcases, Gray"
...,...,...,...,...
1889,TEC-PH-10004912,Technology,Phones,Cisco SPA112 2 Port Phone Adapter
1890,TEC-PH-10004922,Technology,Phones,RCA Visys Integrated PBX 8-Line Router
1891,TEC-PH-10004924,Technology,Phones,"SKILCRAFT Telephone Shoulder Rest, 2"" x 6.5"" x..."
1892,TEC-PH-10004959,Technology,Phones,Classic Ivory AntiqueTelephoneZL1810
1893,TEC-PH-10004977,Technology,Phones,GE 30524EE4

In [37]:
prod.to_excel(
    r"C:\Users\AmanGogna\OneDrive - techcarrot.ae\Desktop\Products_Transformed_again.xlsx",
    index=False
)